/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewPatientIndexRouteImport } from './routes/new-patient/index'
import { Route as MealPlannerIndexRouteImport } from './routes/meal-planner/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as HiThereIndexRouteImport } from './routes/hi/there/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPatientIndexRoute = NewPatientIndexRouteImport.update({
  id: '/new-patient/',
  path: '/new-patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlannerIndexRoute = MealPlannerIndexRouteImport.update({
  id: '/meal-planner/',
  path: '/meal-planner/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const HiThereIndexRoute = HiThereIndexRouteImport.update({
  id: '/hi/there/',
  path: '/hi/there/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn/': typeof LearnIndexRoute
  '/meal-planner/': typeof MealPlannerIndexRoute
  '/new-patient/': typeof NewPatientIndexRoute
  '/hi/there/': typeof HiThereIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn': typeof LearnIndexRoute
  '/meal-planner': typeof MealPlannerIndexRoute
  '/new-patient': typeof NewPatientIndexRoute
  '/hi/there': typeof HiThereIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn/': typeof LearnIndexRoute
  '/meal-planner/': typeof MealPlannerIndexRoute
  '/new-patient/': typeof NewPatientIndexRoute
  '/hi/there/': typeof HiThereIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/learn/' | '/meal-planner/' | '/new-patient/' | '/hi/there/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learn' | '/meal-planner' | '/new-patient' | '/hi/there'
  id:
    | '__root__'
    | '/'
    | '/learn/'
    | '/meal-planner/'
    | '/new-patient/'
    | '/hi/there/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  MealPlannerIndexRoute: typeof MealPlannerIndexRoute
  NewPatientIndexRoute: typeof NewPatientIndexRoute
  HiThereIndexRoute: typeof HiThereIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-patient/': {
      id: '/new-patient/'
      path: '/new-patient'
      fullPath: '/new-patient/'
      preLoaderRoute: typeof NewPatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-planner/': {
      id: '/meal-planner/'
      path: '/meal-planner'
      fullPath: '/meal-planner/'
      preLoaderRoute: typeof MealPlannerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hi/there/': {
      id: '/hi/there/'
      path: '/hi/there'
      fullPath: '/hi/there/'
      preLoaderRoute: typeof HiThereIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  MealPlannerIndexRoute: MealPlannerIndexRoute,
  NewPatientIndexRoute: NewPatientIndexRoute,
  HiThereIndexRoute: HiThereIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
